USE VirtualBar;

INSERT INTO bars (category,drink,image,ingredients,method) VALUES ("whiskey","manhattan","/images/Manhattan.png","2 ounces rye whiskey, bourbon, or Canadian whiskey, 1 ounce sweet vermouth, 2 to 3 dashes Angostura Bitters, Garnish: cherry","Gather the ingredients, Pour the ingredients into a mixing glass with ice cubes,  Stir well Strain into a chilled cocktail glass, Garnish with the cherry");

INSERT INTO bars(category,drink,image,ingredients,method) VALUES ("whiskey", "cocktail's sour","/images/cocktailsSour.png","1 1/2 ounces ​whiskey, 1 1/2 ounces ​lemon juice (fresh), 3/4 ounce ​simple syrup Optional: ​egg white, Garnish: ​​maraschino cherry or lemon peel","Gather the ingredients, In a cocktail shaker filled with ice cubes, pour the ingredients, Shake well Strain into a chilled sour glass or over fresh ice in an old-fashioned glass, Garnish with a cherry or lemon peel");

INSERT INTO bars (category,drink,image,ingredients,method) VALUES ("whiskey","john collins","/images/JohnCollins.png","1 1/2 ounces whiskey (bourbon), 1 ounce lemon (juice of), 1/2 ounce simple syrup, 2​ ounces ​club soda, Garnish: ​​maraschino cherry, Garnish: ​orange slice","Pour the bourbon, lemon juice, and syrup into a collins glass filled with ice cubes, Stir thoroughly, Top with club soda, Garnish with a cherry and orange slice");

INSERT INTO bars(category,drink,image,ingredients,method) VALUES ("whiskey", "Coffee Reciper","/images/CoffeeRecipe.png","4 ounces coffee (strong, rich; brewed, hot), 1 1/2 ounce ​Irish whiskey, 2 teaspoons ​brown sugar, 1 ounce heavy cream (lightly whipped","Gather the ingredients, Place the brown sugar into a warm Irish coffee glass, mug, or other heat-proof glass, Add the coffee and stir until dissolved, Add the Irish whiskey and stir again, Float the lightly whipped heavy cream on top by pouring it over the back of a spoon, Do not stir again. Instead, drink the coffee through the cream");

INSERT INTO bars(category,drink,image,ingredients,method) VALUES ("whiskey", "mint julep","/images/MintJulep.png","4 to 5 mint sprigs (leaves only), 2 sugar cubes (or 1/2 ounce simple syrup), 2 1/2 ounces bourbon whiskey, Garnish: mint sprig","Gather the ingredients, Place the mint leaves and sugar or simple syrup into a julep cup, collins glass, or double old-fashioned glass Muddle well to dissolve the sugar and release the oil and aroma of the mint, Add the bourbon Fill with crushed ice and stir well until the glass becomes frosty, Garnish with a mint sprig");