INSERT INTO whiskey (glass, ingredients, method) VALUES ("manhattan", "2 ounces rye whiskey, bourbon, or Canadian whiskey, 1 ounce sweet vermouth, 2 to 3 dashes Angostura Bitters, Garnish: cherry", "Gather the ingredients, Pour the ingredients into a mixing glass with ice cubes,  Stir well Strain into a chilled cocktail glass, Garnish with the cherry");

INSERT INTO whiskey (glass, ingredients, method) VALUES ("whiskey Sour", "1 1/2 ounces ​whiskey, 1 1/2 ounces ​lemon juice (fresh), 3/4 ounce ​simple syrup Optional: ​egg white, Garnish: ​​maraschino cherry or lemon peel", "Gather the ingredients, In a cocktail shaker filled with ice cubes, pour the ingredients, Shake well Strain into a chilled sour glass or over fresh ice in an old-fashioned glass, Garnish with a cherry or lemon peel");

INSERT INTO whiskey (glass, ingredients, method) VALUES ("John Collins", "1 1/2 ounces whiskey (bourbon), 1 ounce lemon (juice of), 1/2 ounce simple syrup, 2​ ounces ​club soda, Garnish: ​​maraschino cherry, Garnish: ​orange slice", "Pour the bourbon, lemon juice, and syrup into a collins glass filled with ice cubes, Stir thoroughly, Top with club soda, Garnish with a cherry and orange slice");

INSERT INTO whiskey (glass,ingredients, method) VALUES ("Coffee Recipe", "4 ounces coffee (strong, rich; brewed, hot), 1 1/2 ounce ​Irish whiskey, 2 teaspoons ​brown sugar, 1 ounce heavy cream (lightly whipped)", "Gather the ingredients, Place the brown sugar into a warm Irish coffee glass, mug, or other heat-proof glass, Add the coffee and stir until dissolved, Add the Irish whiskey and stir again, Float the lightly whipped heavy cream on top by pouring it over the back of a spoon, Do not stir again. Instead, drink the coffee through the cream");

INSERT INTO whiskey (glass, ingredients, method) VALUES ("Mint Julep", "4 to 5 mint sprigs (leaves only), 2 sugar cubes (or 1/2 ounce simple syrup), 2 1/2 ounces bourbon whiskey, Garnish: mint sprig", "Gather the ingredients, Place the mint leaves and sugar or simple syrup into a julep cup, collins glass, or double old-fashioned glass Muddle well to dissolve the sugar and release the oil and aroma of the mint, Add the bourbon Fill with crushed ice and stir well until the glass becomes frosty, Garnish with a mint sprig");

INSERT INTO whiskey (glass, ingredients, method) VALUES ("Algonquin", "1 1/2 ounces rye whiskey, 3/4 ounce dry vermouth, 3/4 ounce pineapple juice", "Gather the ingredients, In a cocktail shaker filled with ice, pour the rye whiskey, dry vermouth, and pineapple juice, Shake well Strain into a chilled cocktail glass");

INSERT INTO whiskey (glass, ingredients, method) VALUES ("Vieux Carre","3/4 ounce rye whiskey, 3/4 ounce Cognac, 3/4 ounce sweet vermouth, 1/2 ounce Benedictine Liqueur, 1-2 dashes Peychaud Bitters, 1-2 dashes Angostura Aromatic Bitters Garnish: cherry", "Gather the ingredients, Combine the ingredients in a mixing glass filled with ice, Stir well, Strain into an old-fashioned glass filled with ice, Garnish with a cherry" );

INSERT INTO whiskey (glass, ingredients, method) VALUES ("Whiskey Highball", "2 ounces whiskey, 6 ounces ginger ale, or soda", "Gather the ingredients, Fill a highball glass with ice, Pour the whiskey into the glass, Top with ginger ale");

INSERT INTO whiskey (glass, ingredients, method) VALUES ("Lynchburg Lemonade","1 1/2 ounces Jack Daniel's Tennessee Whiskey,1 ounce lemon juice,4 ounces lemon-lime soda", "Gather the ingredients, Pour the whiskey, triple sec, and sour mix into a collins glass filled with ice, Top with soda, Stir well");

INSERT INTO whiskey (glass, ingredients, method) VALUES ("Cobbler","3 ounces whiskey,1/2–1 ounce simple syrup (to taste), Optional: club soda (to fill), Garnish: seasonal fruit or orange and lemon slices with a cherry", "Gather the ingredients, In a wine or old-fashioned glass filled with crushed ice, build the ingredients, Stir well and top with soda, if desired, Add the fruit garnishes (skewered or piled on top of the ice");